import { db } from '@/db';
import { hosts } from '@/db/schema';

async function main() {
    const sampleHosts = [
        {
            fullName: 'Michael Chen',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400',
            contactNumber: '+1-415-234-5678',
            bio: 'Professional property manager with 8+ years experience in luxury vacation rentals. Committed to providing exceptional guest experiences and creating memorable stays for travelers worldwide.',
            createdAt: new Date('2022-03-15').toISOString(),
            updatedAt: new Date('2022-03-15').toISOString(),
        },
        {
            fullName: 'Sarah Johnson',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400',
            contactNumber: '+1-212-567-8901',
            bio: 'Local host sharing unique spaces in beautiful locations. Passionate about hospitality and creating memorable stays. Love connecting with guests from around the world.',
            createdAt: new Date('2022-06-20').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            fullName: 'Carlos Rodriguez',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400',
            contactNumber: '+1-310-789-0123',
            bio: 'Family-owned properties managed with care. We love welcoming guests and sharing local insights. Three generations of hospitality experience in coastal properties.',
            createdAt: new Date('2022-08-12').toISOString(),
            updatedAt: new Date('2022-08-12').toISOString(),
        },
        {
            fullName: 'Aisha Patel',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400',
            contactNumber: '+1-617-345-6789',
            bio: 'Boutique hospitality specialist with focus on eco-friendly accommodations. Dedicated to sustainable tourism and authentic cultural experiences for every guest.',
            createdAt: new Date('2023-01-05').toISOString(),
            updatedAt: new Date('2023-01-05').toISOString(),
        },
        {
            fullName: 'James O\'Connor',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400',
            contactNumber: '+1-305-901-2345',
            bio: 'Experienced host of waterfront properties for over a decade. Specializing in luxury retreats with personalized service and attention to every detail.',
            createdAt: new Date('2022-04-18').toISOString(),
            updatedAt: new Date('2023-11-20').toISOString(),
        },
        {
            fullName: 'Maria Santos',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400',
            contactNumber: '+1-512-456-7890',
            bio: 'Welcoming travelers to charming historic properties. Expert in local culture and cuisine. Passionate about making every stay feel like home away from home.',
            createdAt: new Date('2023-02-28').toISOString(),
            updatedAt: new Date('2023-02-28').toISOString(),
        },
        {
            fullName: 'David Kim',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400',
            contactNumber: '+1-206-678-9012',
            bio: 'Tech-savvy host offering modern smart homes with cutting-edge amenities. Former software engineer turned hospitality entrepreneur with properties in major tech hubs.',
            createdAt: new Date('2023-05-10').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            fullName: 'Isabella Rossi',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400',
            contactNumber: '+1-303-234-5678',
            bio: 'Curating authentic Italian-inspired experiences in mountain retreats. Interior designer by trade, bringing artistic touch to every property and guest interaction.',
            createdAt: new Date('2022-09-22').toISOString(),
            updatedAt: new Date('2022-09-22').toISOString(),
        },
        {
            fullName: 'Ahmed Hassan',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&h=400',
            contactNumber: '+1-404-890-1234',
            bio: 'Professional host managing urban apartments and business traveler accommodations. Known for seamless check-ins, impeccable cleanliness, and responsive communication.',
            createdAt: new Date('2023-03-14').toISOString(),
            updatedAt: new Date('2023-03-14').toISOString(),
        },
        {
            fullName: 'Emily Foster',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400',
            contactNumber: '+1-713-567-8901',
            bio: 'Pet-friendly property specialist welcoming furry family members. Certified animal care professional managing comfortable spaces for pets and their humans.',
            createdAt: new Date('2022-11-08').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            fullName: 'Yuki Tanaka',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400',
            contactNumber: '+1-415-789-0123',
            bio: 'Zen-inspired minimalist properties in serene settings. Background in wellness hospitality, creating peaceful retreats for relaxation and rejuvenation.',
            createdAt: new Date('2023-06-19').toISOString(),
            updatedAt: new Date('2023-06-19').toISOString(),
        },
        {
            fullName: 'Sophie Dubois',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=400',
            contactNumber: '+1-212-345-6789',
            bio: 'French hospitality meets American comfort. Managing boutique properties with European flair and attention to detail. Fluent in five languages for international guests.',
            createdAt: new Date('2022-07-25').toISOString(),
            updatedAt: new Date('2023-09-12').toISOString(),
        },
        {
            fullName: 'Raj Kumar',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400',
            contactNumber: '+1-310-901-2345',
            bio: 'Hospitality industry veteran with 15+ years experience. Specializing in beachfront properties and tropical getaways. Award-winning host with perfect ratings.',
            createdAt: new Date('2022-05-11').toISOString(),
            updatedAt: new Date('2022-05-11').toISOString(),
        },
        {
            fullName: 'Anna Kowalski',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400',
            contactNumber: '+1-617-456-7890',
            bio: 'Managing cozy countryside cottages and rustic farmstays. Former chef offering culinary experiences and farm-to-table breakfast options for guests.',
            createdAt: new Date('2023-04-07').toISOString(),
            updatedAt: new Date('2023-04-07').toISOString(),
        },
        {
            fullName: 'Marcus Thompson',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=400&h=400',
            contactNumber: '+1-305-678-9012',
            bio: 'Sports enthusiast hosting properties near stadiums and athletic venues. Specializing in accommodations for sports fans and event-goers with insider local knowledge.',
            createdAt: new Date('2023-08-16').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            fullName: 'Priya Sharma',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400',
            contactNumber: '+1-512-234-5678',
            bio: 'Wellness retreat specialist offering yoga-friendly spaces and meditation gardens. Certified wellness coach creating holistic experiences for mind, body, and soul.',
            createdAt: new Date('2022-10-30').toISOString(),
            updatedAt: new Date('2022-10-30').toISOString(),
        },
        {
            fullName: 'Lucas Silva',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400',
            contactNumber: '+1-206-890-1234',
            bio: 'Adventure travel specialist managing properties near national parks and hiking trails. Outdoor enthusiast sharing passion for nature with eco-conscious travelers.',
            createdAt: new Date('2023-01-22').toISOString(),
            updatedAt: new Date('2023-01-22').toISOString(),
        },
        {
            fullName: 'Fatima Ali',
            userId: null,
            profilePicture: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400',
            contactNumber: '+1-303-567-8901',
            bio: 'Cultural ambassador hosting unique heritage properties. Expert in local history and traditions, offering authentic cultural immersion experiences to international visitors.',
            createdAt: new Date('2023-07-03').toISOString(),
            updatedAt: new Date('2023-12-18').toISOString(),
        },
    ];

    await db.insert(hosts).values(sampleHosts);
    
    console.log(`✅ Hosts seeder completed successfully - Created ${sampleHosts.length} hosts`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});