import { db } from '@/db';
import { peakSeasonRates } from '@/db/schema';

async function main() {
    const samplePeakSeasonRates = [
        // Christmas Week 2025 - All 5 rooms
        {
            propertyId: 1,
            roomId: 1,
            startDate: '2024-12-24',
            endDate: '2024-12-31',
            priceIncrease: 150000,
            percentageIncrease: 30.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 2,
            startDate: '2024-12-24',
            endDate: '2024-12-31',
            priceIncrease: 120000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 3,
            startDate: '2024-12-24',
            endDate: '2024-12-31',
            priceIncrease: null,
            percentageIncrease: 30.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 4,
            startDate: '2024-12-24',
            endDate: '2024-12-31',
            priceIncrease: 150000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 5,
            startDate: '2024-12-24',
            endDate: '2024-12-31',
            priceIncrease: 90000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // New Year Week 2026 - All 5 rooms
        {
            propertyId: 1,
            roomId: 1,
            startDate: '2025-01-01',
            endDate: '2025-01-07',
            priceIncrease: 120000,
            percentageIncrease: 25.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 2,
            startDate: '2025-01-01',
            endDate: '2025-01-07',
            priceIncrease: 100000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 3,
            startDate: '2025-01-01',
            endDate: '2025-01-07',
            priceIncrease: null,
            percentageIncrease: 25.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 4,
            startDate: '2025-01-01',
            endDate: '2025-01-07',
            priceIncrease: 120000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 5,
            startDate: '2025-01-01',
            endDate: '2025-01-07',
            priceIncrease: 75000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Weekend Premium Rates - First 3 weekends of February 2025 (Rooms 1, 3, 5)
        {
            propertyId: 1,
            roomId: 1,
            startDate: '2025-02-01',
            endDate: '2025-02-02',
            priceIncrease: 80000,
            percentageIncrease: 20.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 3,
            startDate: '2025-02-08',
            endDate: '2025-02-09',
            priceIncrease: null,
            percentageIncrease: 20.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 5,
            startDate: '2025-02-15',
            endDate: '2025-02-16',
            priceIncrease: 50000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Weekend Premium Rates - First 3 weekends of March 2025 (Rooms 2, 4)
        {
            propertyId: 1,
            roomId: 2,
            startDate: '2025-03-01',
            endDate: '2025-03-02',
            priceIncrease: 60000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 4,
            startDate: '2025-03-08',
            endDate: '2025-03-09',
            priceIncrease: null,
            percentageIncrease: 20.0,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            roomId: 2,
            startDate: '2025-03-15',
            endDate: '2025-03-16',
            priceIncrease: 60000,
            percentageIncrease: null,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(peakSeasonRates).values(samplePeakSeasonRates);
    
    console.log('✅ Peak season rates seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});