import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        // Jakarta - Kemang (3 properties)
        {
            name: 'Modern 2BR Apartment in Kemang',
            type: 'Apartment',
            price: 850000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: true,
            description: 'Experience luxury living in the heart of Kemang, Jakarta\'s most vibrant neighborhood. This modern 2-bedroom apartment features floor-to-ceiling windows, contemporary furnishings, and a fully equipped kitchen. Located within walking distance to trendy cafes, restaurants, and boutiques. The building offers 24-hour security, a rooftop pool, and fitness center. Perfect for business travelers and couples seeking a sophisticated urban retreat.',
            address: 'Jl. Kemang Raya No. 45',
            country: 'Indonesia',
            latitude: -6.264352,
            longitude: 106.814928,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Washing Machine']),
            isPublished: true,
            hostId: 1,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Cozy Studio in Kemang Village',
            type: 'Apartment',
            price: 450000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
            isGuestFavorite: false,
            description: 'Charming studio apartment in the popular Kemang Village complex. This compact yet efficiently designed space features a comfortable queen bed, kitchenette, and modern bathroom. The complex offers easy access to shopping centers, international restaurants, and entertainment venues. Ideal for solo travelers or couples on a budget who want to experience Jakarta\'s expatriate lifestyle. Includes access to shared pool and garden area.',
            address: 'Kemang Village, Jl. Pangeran Antasari',
            country: 'Indonesia',
            latitude: -6.265421,
            longitude: 106.813245,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchenette', 'TV', 'Security']),
            isPublished: true,
            hostId: 3,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Luxurious 3BR Penthouse Kemang',
            type: 'Apartment',
            price: 1500000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
            isGuestFavorite: true,
            description: 'Spectacular penthouse offering breathtaking city views and unparalleled luxury in Kemang. This 3-bedroom residence spans 200 square meters with a private terrace, jacuzzi, and premium furnishings throughout. Features include a gourmet kitchen with top-tier appliances, spacious living areas, and three en-suite bathrooms. The building provides concierge service, private elevator access, and exclusive amenities. Perfect for families or groups seeking the ultimate Jakarta experience.',
            address: 'Jl. Kemang Selatan No. 99',
            country: 'Indonesia',
            latitude: -6.266789,
            longitude: 106.815432,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Washing Machine', 'Jacuzzi', 'Terrace', 'Concierge']),
            isPublished: true,
            hostId: 5,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Jakarta - Senopati (3 properties)
        {
            name: 'Stylish Loft in Senopati',
            type: 'Apartment',
            price: 750000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
            isGuestFavorite: true,
            description: 'Contemporary loft-style apartment in the heart of Senopati\'s dining district. High ceilings, exposed brick walls, and industrial-chic design create a unique living space. The open-plan layout includes a designer kitchen, comfortable living area, and mezzanine bedroom. Located steps away from Jakarta\'s best restaurants, bars, and galleries. Building amenities include rooftop lounge and co-working space. Ideal for creative professionals and food enthusiasts.',
            address: 'Jl. Senopati No. 72',
            country: 'Indonesia',
            latitude: -6.234521,
            longitude: 106.809876,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800',
                'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'TV', 'Workspace', 'Rooftop Access']),
            isPublished: true,
            hostId: 7,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Elegant 2BR Apartment Senopati',
            type: 'Apartment',
            price: 900000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            description: 'Beautifully designed 2-bedroom apartment offering modern comfort in Senopati. Features elegant interiors with quality furnishings, a fully equipped kitchen, and spacious balcony overlooking the cityscape. Walking distance to numerous restaurants, cafes, and nightlife venues. The building provides 24-hour security, gym facilities, and covered parking. Perfect for small families or business travelers seeking a central location with excellent dining options nearby.',
            address: 'Jl. Senopati Raya No. 88',
            country: 'Indonesia',
            latitude: -6.235678,
            longitude: 106.808765,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Gym', 'Parking', 'TV', 'Balcony']),
            isPublished: true,
            hostId: 9,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Modern Studio Near Senopati',
            type: 'Apartment',
            price: 500000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Compact and efficient studio apartment near Senopati\'s vibrant street. Features minimalist design with comfortable sleeping arrangements, workspace area, and modern bathroom. Perfect for solo travelers or digital nomads. Close proximity to Metro department store, restaurants, and public transportation. Building offers reliable WiFi, air conditioning, and friendly management. Great value for those wanting to experience Jakarta\'s culinary scene without breaking the bank.',
            address: 'Jl. Cipaku I No. 15',
            country: 'Indonesia',
            latitude: -6.236543,
            longitude: 106.807654,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV', 'Workspace']),
            isPublished: true,
            hostId: 11,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },

        // Jakarta - Menteng (3 properties)
        {
            name: 'Colonial House in Menteng',
            type: 'House',
            price: 1200000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: true,
            description: 'Charming colonial-era house in prestigious Menteng neighborhood, Jakarta\'s historic garden city. This beautifully preserved property features high ceilings, wooden floors, and classic architectural details. Three spacious bedrooms, landscaped garden, and shaded terrace create a peaceful oasis in the city center. Walking distance to Taman Suropati park and traditional Indonesian restaurants. Includes housekeeping service and private parking. Ideal for families seeking authentic Jakarta heritage experience.',
            address: 'Jl. Menteng Raya No. 12',
            country: 'Indonesia',
            latitude: -6.188234,
            longitude: 106.836789,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Housekeeping', 'Terrace']),
            isPublished: true,
            hostId: 2,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Luxury Apartment Menteng',
            type: 'Apartment',
            price: 950000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
            isGuestFavorite: false,
            description: 'Premium 2-bedroom apartment in one of Menteng\'s finest residential towers. Featuring marble floors, designer furniture, and panoramic city views. The apartment offers spacious living areas, fully equipped kitchen with modern appliances, and two en-suite bathrooms. Building amenities include infinity pool, state-of-the-art gym, and 24-hour concierge. Located near embassies, upscale shopping, and business districts. Perfect for executives and discerning travelers.',
            address: 'Jl. HOS Cokroaminoto No. 88',
            country: 'Indonesia',
            latitude: -6.189456,
            longitude: 106.835432,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Concierge']),
            isPublished: true,
            hostId: 4,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Heritage Guesthouse Menteng',
            type: 'Guesthouse',
            price: 650000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
            isGuestFavorite: false,
            description: 'Boutique guesthouse in restored Menteng residence offering authentic Indonesian hospitality. Two comfortable bedrooms with traditional decor, shared living spaces, and lush tropical garden. Daily breakfast included featuring local and western options. The property manager provides personalized recommendations for exploring Jakarta. Close to Museum of Fine Arts and historic landmarks. Ideal for cultural enthusiasts and travelers seeking local experiences in elegant surroundings.',
            address: 'Jl. Sumenep No. 7',
            country: 'Indonesia',
            latitude: -6.190234,
            longitude: 106.834567,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Breakfast', 'TV']),
            isPublished: true,
            hostId: 6,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },

        // Jakarta - Sudirman (3 properties)
        {
            name: 'Executive Suite Sudirman',
            type: 'Apartment',
            price: 1100000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
            isGuestFavorite: true,
            description: 'Sophisticated executive apartment in Jakarta\'s prime business district. This modern suite features floor-to-ceiling windows with stunning skyline views, contemporary furnishings, and high-speed internet. The spacious layout includes a work area, fully equipped kitchen, and luxurious bathroom with rain shower. Direct access to shopping malls, international restaurants, and corporate offices. Building offers premium amenities including rooftop pool, business center, and valet parking.',
            address: 'Jl. Jenderal Sudirman Kav. 52',
            country: 'Indonesia',
            latitude: -6.224876,
            longitude: 106.809234,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Workspace', 'Business Center']),
            isPublished: true,
            hostId: 8,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Premium 2BR Sudirman Tower',
            type: 'Apartment',
            price: 1300000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: true,
            description: 'Exclusive 2-bedroom apartment on high floor of prestigious Sudirman tower. Offers panoramic views of Jakarta skyline and mountains. Features include Italian marble, designer kitchen with premium appliances, and smart home technology. Two master bedrooms with en-suite bathrooms and walk-in closets. Building provides 5-star hotel services including concierge, spa, and fine dining restaurant. Perfect for corporate executives and luxury travelers seeking uncompromising quality.',
            address: 'Jl. Jenderal Sudirman Kav. 76',
            country: 'Indonesia',
            latitude: -6.225987,
            longitude: 106.808123,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Spa', 'Concierge', 'Smart Home']),
            isPublished: true,
            hostId: 10,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Business Apartment Sudirman',
            type: 'Apartment',
            price: 800000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Practical business apartment designed for working professionals. Features efficient layout with dedicated workspace, high-speed WiFi, and all essential amenities. Located in mixed-use complex with direct mall access, restaurants, and business facilities. Walking distance to major office buildings and public transportation. Apartment includes weekly housekeeping and laundry service. Ideal for extended business stays or corporate relocations requiring comfortable, functional accommodation.',
            address: 'Jl. Jenderal Sudirman Kav. 45',
            country: 'Indonesia',
            latitude: -6.223456,
            longitude: 106.810567,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Workspace', 'TV', 'Housekeeping', 'Laundry']),
            isPublished: true,
            hostId: 12,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },

        // Jakarta - Kuningan (3 properties)
        {
            name: 'Serviced Apartment Kuningan',
            type: 'Apartment',
            price: 950000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
            isGuestFavorite: true,
            description: 'Premium serviced apartment in Kuningan business district. Offers hotel-quality service with apartment flexibility. Features modern design, fully equipped kitchen, spacious living area, and comfortable bedroom. Daily housekeeping, linen change, and 24-hour reception included. Building amenities include swimming pool, fitness center, and business lounge. Located near embassies, major hotels, and shopping centers. Perfect for business travelers and expatriates seeking long-term accommodation with full services.',
            address: 'Jl. HR Rasuna Said Kav. C-11',
            country: 'Indonesia',
            latitude: -6.223789,
            longitude: 106.830456,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'TV', 'Housekeeping', 'Reception']),
            isPublished: true,
            hostId: 13,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Family Suite Kuningan City',
            type: 'Apartment',
            price: 1100000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
            isGuestFavorite: false,
            description: 'Spacious 2-bedroom family apartment in Kuningan City complex. Features open-plan living and dining area, modern kitchen, and two comfortable bedrooms. Direct access to shopping mall with supermarket, cinema, and kids play area. The apartment includes high-speed WiFi, smart TV, and washing machine. Building offers swimming pool, children\'s pool, and playground. Ideal for families wanting convenience of integrated lifestyle complex with entertainment and shopping at doorstep.',
            address: 'Kuningan City, Jl. Prof. Dr. Satrio',
            country: 'Indonesia',
            latitude: -6.224567,
            longitude: 106.829876,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 5,
            petsAllowed: true,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'TV', 'Washing Machine', 'Mall Access', 'Playground']),
            isPublished: true,
            hostId: 14,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Modern Studio Kuningan',
            type: 'Apartment',
            price: 550000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Affordable studio apartment in Kuningan area perfect for solo travelers. Clean, comfortable space with essential amenities including WiFi, air conditioning, and kitchenette. Located in quiet residential building with good security. Walking distance to restaurants, convenience stores, and public transportation. The apartment offers excellent value for budget-conscious travelers who want to stay in Jakarta\'s business district without premium prices. Weekly housekeeping service available upon request.',
            address: 'Jl. Kuningan Barat No. 28',
            country: 'Indonesia',
            latitude: -6.225234,
            longitude: 106.828765,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV', 'Security']),
            isPublished: true,
            hostId: 15,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },

        // Tangerang - BSD (2 properties)
        {
            name: 'Modern House BSD City',
            type: 'House',
            price: 1000000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: true,
            description: 'Beautiful modern house in BSD City, Indonesia\'s premier satellite township. This 3-bedroom property features contemporary architecture, spacious rooms, and private garden. Fully furnished with quality furniture, modern kitchen appliances, and comfortable living spaces. Located in secure gated community with easy access to shopping malls, international schools, and business parks. Includes parking for two cars. Perfect for families relocating to Jakarta area or groups wanting suburban comfort with city accessibility.',
            address: 'BSD City, Jl. Letnan Sutopo',
            country: 'Indonesia',
            latitude: -6.301689,
            longitude: 106.663456,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Washing Machine', 'Security']),
            isPublished: true,
            hostId: 16,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Cozy Apartment BSD Green Office',
            type: 'Apartment',
            price: 650000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Comfortable apartment in BSD Green Office Park area. One-bedroom unit with modern amenities and functional layout. Located in building with direct access to office parks, shopping centers, and dining options. Features include well-equipped kitchen, comfortable workspace, and balcony with garden view. Building offers swimming pool and fitness center. Ideal for business travelers working in BSD area or couples seeking suburban living with urban conveniences close to Jakarta.',
            address: 'BSD Green Office Park, Jl. BSD Grand Boulevard',
            country: 'Indonesia',
            latitude: -6.302876,
            longitude: 106.662345,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'TV', 'Workspace', 'Balcony']),
            isPublished: true,
            hostId: 17,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // Tangerang - Gading Serpong (2 properties)
        {
            name: 'Luxury Villa Gading Serpong',
            type: 'Villa',
            price: 1500000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Stunning luxury villa in exclusive Gading Serpong residential area. This spacious property features 4 bedrooms, private swimming pool, tropical garden, and outdoor pavilion. Interior showcases high-end furnishings, modern kitchen with premium appliances, and elegant living spaces. The villa offers complete privacy with 24-hour security. Perfect for family gatherings, corporate retreats, or special celebrations. Located near Summarecon Mall, international schools, and golf courses.',
            address: 'Gading Serpong, Jl. Boulevard Gading Serpong',
            country: 'Indonesia',
            latitude: -6.242567,
            longitude: 106.625789,
            bedrooms: 4,
            bathrooms: 3,
            maxGuests: 8,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Parking', 'TV', 'BBQ', 'Security']),
            isPublished: true,
            hostId: 18,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Family Apartment Gading Serpong',
            type: 'Apartment',
            price: 750000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            description: 'Spacious 2-bedroom family apartment in Gading Serpong. Features comfortable living room, fully equipped kitchen, and two bedrooms with quality beds. Located in family-friendly complex with children\'s playground, swimming pool, and jogging track. Close to Summarecon Mall, restaurants, and entertainment venues. The apartment includes WiFi, air conditioning, and parking space. Ideal for families wanting suburban lifestyle with mall access and green environment away from Jakarta traffic.',
            address: 'Gading Serpong, Jl. Gading Golf Boulevard',
            country: 'Indonesia',
            latitude: -6.243456,
            longitude: 106.624678,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 5,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Playground', 'Parking', 'TV']),
            isPublished: true,
            hostId: 1,
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Tangerang - Alam Sutera (2 properties)
        {
            name: 'Modern House Alam Sutera',
            type: 'House',
            price: 1100000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: true,
            description: 'Contemporary house in prestigious Alam Sutera township. This 3-bedroom property features modern minimalist design, open-plan living area, and private backyard. Fully furnished with stylish furniture and equipped kitchen. Located in secure compound near Living World mall, international hospitals, and business districts. Includes high-speed WiFi, air conditioning throughout, and parking for two vehicles. Perfect for expatriate families or corporate housing requiring quality accommodation in planned community.',
            address: 'Alam Sutera, Jl. Jalur Sutera Barat',
            country: 'Indonesia',
            latitude: -6.227890,
            longitude: 106.663245,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Washing Machine', 'Security']),
            isPublished: true,
            hostId: 2,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            name: 'Studio Apartment Alam Sutera',
            type: 'Apartment',
            price: 500000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Efficient studio apartment in Alam Sutera area. Clean and comfortable space with modern amenities perfect for solo travelers or couples. Features kitchenette, comfortable bed, and workspace area. Located in residential building with good security and reliable WiFi. Close to Living World shopping center, restaurants, and business parks. The apartment offers great value for those working in Alam Sutera area or seeking affordable accommodation near Jakarta with better air quality.',
            address: 'Alam Sutera, Jl. Sutera Utama',
            country: 'Indonesia',
            latitude: -6.228765,
            longitude: 106.662134,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV', 'Workspace', 'Security']),
            isPublished: true,
            hostId: 3,
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },

        // Tangerang - Serpong (2 properties)
        {
            name: 'Townhouse Serpong Garden',
            type: 'House',
            price: 900000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: false,
            description: 'Comfortable townhouse in Serpong Garden residential estate. This 2-story property features 3 bedrooms, spacious living area, and small garden. Modern kitchen with essential appliances, dining area, and two bathrooms. Located in safe gated community with 24-hour security. Close to shopping centers, schools, and hospital facilities. The townhouse includes parking space and basic furnishings. Suitable for families or groups wanting peaceful suburban setting with easy access to Jakarta via toll road.',
            address: 'Serpong Garden, Jl. Raya Serpong',
            country: 'Indonesia',
            latitude: -6.298765,
            longitude: 106.671234,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Security']),
            isPublished: true,
            hostId: 4,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: 'Apartment Serpong Business Park',
            type: 'Apartment',
            price: 600000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Practical apartment near Serpong business and education hub. One bedroom with modern furnishings, fully equipped kitchen, and comfortable living space. Located in building with swimming pool and fitness center. Walking distance to universities, business parks, and shopping areas. The apartment features reliable WiFi, air conditioning, and parking access. Ideal for students, young professionals, or business travelers working in Serpong area seeking convenient, affordable accommodation.',
            address: 'Serpong, Jl. Pahlawan Seribu',
            country: 'Indonesia',
            latitude: -6.297654,
            longitude: 106.670123,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV']),
            isPublished: true,
            hostId: 5,
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },

        // Tangerang - Bintaro (4 properties)
        {
            name: 'Modern Villa Bintaro Jaya',
            type: 'Villa',
            price: 1400000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Elegant villa in prestigious Bintaro Jaya residential area. This luxurious property features 4 bedrooms, private pool, spacious garden, and modern architecture. Interior includes high-quality furnishings, gourmet kitchen, and multiple living areas. Located in secure gated community near international school, golf course, and shopping centers. The villa offers complete privacy and comfort for families or groups. Includes housekeeping service, gardener, and security. Perfect for special occasions or extended family stays.',
            address: 'Bintaro Jaya Sektor 9, Jl. Bintaro Utama',
            country: 'Indonesia',
            latitude: -6.269876,
            longitude: 106.740123,
            bedrooms: 4,
            bathrooms: 3,
            maxGuests: 8,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Parking', 'TV', 'Housekeeping', 'BBQ', 'Security']),
            isPublished: true,
            hostId: 6,
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        {
            name: 'Family House Bintaro',
            type: 'House',
            price: 950000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: false,
            description: 'Spacious family house in established Bintaro neighborhood. Three bedrooms, comfortable living spaces, and functional kitchen make this ideal for families. Located in quiet residential area with parks, schools, and shopping nearby. The house features air conditioning, WiFi, and parking for two cars. Property includes small garden and covered patio. Close to Exchange Mall and various dining options. Suitable for families relocating or extended stays requiring home comfort in suburban setting.',
            address: 'Bintaro Sektor 7, Jl. Bintaro Raya',
            country: 'Indonesia',
            latitude: -6.270765,
            longitude: 106.739012,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Patio']),
            isPublished: true,
            hostId: 7,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: 'Cozy 2BR Apartment Bintaro Plaza',
            type: 'Apartment',
            price: 700000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            description: 'Comfortable 2-bedroom apartment near Bintaro Plaza. Features modern design, fully equipped kitchen, and pleasant living area. Located in building with swimming pool and parking facilities. Walking distance to Bintaro Plaza shopping center, restaurants, and Commuter Line station. The apartment includes WiFi, air conditioning, and weekly housekeeping option. Ideal for small families or business travelers wanting convenient access to both Jakarta and suburban amenities in established community.',
            address: 'Bintaro Plaza Residence, Jl. Bintaro Utama',
            country: 'Indonesia',
            latitude: -6.271654,
            longitude: 106.737901,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Parking', 'TV', 'Housekeeping']),
            isPublished: true,
            hostId: 8,
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-04-08').toISOString(),
        },
        {
            name: 'Studio Apartment Bintaro',
            type: 'Apartment',
            price: 450000,
            nights: 2,
            rating: 4.3,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Affordable studio apartment in Bintaro area perfect for solo travelers or couples. Clean, functional space with essential amenities including kitchenette, comfortable bed, and modern bathroom. Located in residential building near public transportation and local markets. The apartment offers good value with WiFi, air conditioning, and basic furnishings. Close to Commuter Line station for easy access to Jakarta. Ideal for budget-conscious travelers or workers needing simple, comfortable accommodation in suburban setting.',
            address: 'Bintaro Sektor 1, Jl. Jurangmangu Timur',
            country: 'Indonesia',
            latitude: -6.272543,
            longitude: 106.736790,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV']),
            isPublished: true,
            hostId: 9,
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },

        // Bali - Seminyak (3 properties)
        {
            name: 'Luxury Beachfront Villa Seminyak',
            type: 'Villa',
            price: 2000000,
            nights: 2,
            rating: 5.0,
            imageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
            isGuestFavorite: true,
            description: 'Stunning beachfront villa in prestigious Seminyak area. This exclusive property features 5 bedrooms, infinity pool overlooking the ocean, tropical garden, and traditional Balinese architecture with modern luxury. Interior showcases elegant furnishings, state-of-the-art kitchen, and spacious living pavilions. Staff includes chef, housekeepers, and garden maintenance. Located steps from beach, walking distance to trendy restaurants, beach clubs, and boutiques. Perfect for special celebrations or luxury family holidays in paradise.',
            address: 'Jl. Camplung Tanduk, Seminyak',
            country: 'Indonesia',
            latitude: -8.691845,
            longitude: 115.165234,
            bedrooms: 5,
            bathrooms: 4,
            maxGuests: 10,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Beach Access', 'Kitchen', 'Garden', 'Staff', 'TV', 'BBQ', 'Security']),
            isPublished: true,
            hostId: 10,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Modern 3BR Villa Seminyak',
            type: 'Villa',
            price: 1500000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Contemporary 3-bedroom villa in heart of Seminyak. Features private pool, lush tropical garden, and modern Balinese design. The villa includes open-plan living area, fully equipped kitchen, and three comfortable bedrooms with en-suite bathrooms. Located within walking distance to Oberoi Street restaurants, Seminyak Square, and beaches. Daily housekeeping included. Perfect for families or groups wanting privacy, comfort, and easy access to Seminyak\'s vibrant dining and nightlife scene.',
            address: 'Jl. Oberoi, Seminyak',
            country: 'Indonesia',
            latitude: -8.692734,
            longitude: 115.164123,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Housekeeping', 'TV', 'BBQ']),
            isPublished: true,
            hostId: 11,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Chic 2BR Apartment Seminyak',
            type: 'Apartment',
            price: 900000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Stylish 2-bedroom apartment in boutique complex near Seminyak beach. Features contemporary design, shared pool, and rooftop lounge. The apartment includes modern kitchen, comfortable living space, and two bedrooms with quality beds. Located minutes walk to beach, restaurants, and shopping. Complex offers security and daily cleaning service. Ideal for couples or small families wanting resort-style living with hotel amenities in prime Seminyak location without villa price tag.',
            address: 'Jl. Kayu Aya, Seminyak',
            country: 'Indonesia',
            latitude: -8.693623,
            longitude: 115.163012,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'TV', 'Housekeeping', 'Rooftop']),
            isPublished: true,
            hostId: 12,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },

        // Bali - Canggu (3 properties)
        {
            name: 'Surf Villa Canggu Beach',
            type: 'Villa',
            price: 1400000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Stunning surf villa steps from Canggu beach. This 3-bedroom property features infinity pool, open living pavilion, and tropical garden with rice field views. Perfect for surf enthusiasts with board storage and outdoor shower. Modern interior with fully equipped kitchen, comfortable bedrooms, and contemporary Balinese design. Walking distance to popular beach clubs, cafes, and surf spots. Daily housekeeping included. Ideal for active travelers seeking authentic Canggu lifestyle and surf culture.',
            address: 'Jl. Pantai Batu Bolong, Canggu',
            country: 'Indonesia',
            latitude: -8.648901,
            longitude: 115.138567,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Outdoor Shower', 'Surf Storage', 'Housekeeping', 'TV']),
            isPublished: true,
            hostId: 13,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Eco Villa Canggu Rice Fields',
            type: 'Villa',
            price: 1200000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Eco-friendly villa surrounded by rice fields in peaceful Canggu area. This sustainable property features 2 bedrooms, natural pool, open-air living spaces, and organic garden. Built with reclaimed wood and natural materials, offering authentic Balinese experience. Includes solar panels, rainwater harvesting, and composting. Located away from crowds yet close to beaches and restaurants. Perfect for environmentally conscious travelers seeking tranquility, nature connection, and sustainable luxury in Bali.',
            address: 'Jl. Canggu Padang Linjong',
            country: 'Indonesia',
            latitude: -8.649790,
            longitude: 115.137456,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'Natural Pool', 'Kitchen', 'Garden', 'Rice Field View', 'Eco-Friendly', 'Yoga Space', 'Housekeeping']),
            isPublished: true,
            hostId: 14,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Modern Guesthouse Canggu',
            type: 'Guesthouse',
            price: 600000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
            isGuestFavorite: false,
            description: 'Contemporary guesthouse in vibrant Canggu community. Features comfortable room with en-suite bathroom, access to shared pool, and communal areas. Located in compound with other villas, offering social atmosphere while maintaining privacy. Walking distance to Canggu\'s best cafes, coworking spaces, and beaches. Includes breakfast, WiFi, and daily room service. Perfect for digital nomads, solo travelers, or couples wanting affordable Canggu lifestyle with community vibe and modern amenities.',
            address: 'Jl. Raya Canggu No. 88',
            country: 'Indonesia',
            latitude: -8.650679,
            longitude: 115.136345,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Breakfast', 'TV', 'Housekeeping', 'Coworking']),
            isPublished: true,
            hostId: 15,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },

        // Bali - Ubud (3 properties)
        {
            name: 'Luxury Jungle Villa Ubud',
            type: 'Villa',
            price: 1800000,
            nights: 2,
            rating: 5.0,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Spectacular jungle villa in Ubud rainforest. This 4-bedroom property features infinity pool overlooking valley, open-air pavilions, and traditional Balinese architecture. Interior showcases antique furnishings, art collection, and luxurious bathrooms with outdoor showers. Full staff including chef, butler, and spa therapist available. Located minutes from Ubud center, monkey forest, and art galleries. Perfect for wellness retreats, honeymoons, or luxury escapes seeking tranquility, culture, and natural beauty.',
            address: 'Jl. Raya Pengosekan, Ubud',
            country: 'Indonesia',
            latitude: -8.519876,
            longitude: 115.264789,
            bedrooms: 4,
            bathrooms: 4,
            maxGuests: 8,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Valley View', 'Staff', 'Spa', 'Yoga', 'TV']),
            isPublished: true,
            hostId: 16,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Traditional Ubud House',
            type: 'House',
            price: 1000000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: true,
            description: 'Authentic Balinese house in peaceful Ubud neighborhood. This 3-bedroom traditional property features carved wooden doors, stone courtyards, and tropical garden with lotus pond. Interior combines antique furniture with modern comfort. Includes private pool, outdoor dining area, and meditation space. Located near rice terraces and walking distance to Ubud Palace, markets, and restaurants. Daily offerings and housekeeping included. Perfect for cultural immersion and experiencing traditional Balinese lifestyle.',
            address: 'Jl. Monkey Forest, Ubud',
            country: 'Indonesia',
            latitude: -8.520765,
            longitude: 115.263678,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Meditation Space', 'Housekeeping', 'TV']),
            isPublished: true,
            hostId: 17,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Boutique Hotel Room Ubud Center',
            type: 'Hotel',
            price: 700000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
            isGuestFavorite: false,
            description: 'Elegant room in boutique hotel in Ubud center. Features Balinese design with modern amenities, private balcony overlooking garden, and luxurious bathroom. Hotel offers infinity pool, spa services, yoga classes, and restaurant serving organic cuisine. Located walking distance to Ubud Market, art galleries, and temples. Daily breakfast and room service included. Perfect for travelers wanting hotel comfort and services while exploring Ubud\'s art, culture, and wellness scene.',
            address: 'Jl. Raya Ubud No. 35',
            country: 'Indonesia',
            latitude: -8.521654,
            longitude: 115.262567,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
                'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Breakfast', 'Spa', 'Yoga', 'Restaurant', 'TV', 'Balcony']),
            isPublished: true,
            hostId: 18,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },

        // Bali - Sanur (3 properties)
        {
            name: 'Beachfront Villa Sanur',
            type: 'Villa',
            price: 1600000,
            nights: 2,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
            isGuestFavorite: true,
            description: 'Exclusive beachfront villa on Sanur\'s peaceful coastline. This 4-bedroom property features direct beach access, beachfront pool, and traditional Balinese pavilions. Interior includes elegant furnishings, modern kitchen, and spacious living areas. Staff includes housekeeper and gardener. Located on quiet Sanur beach, walking distance to restaurants and beachfront promenade. Perfect for families seeking tranquil beach holiday with sunrise views, water sports, and relaxed atmosphere away from crowded tourist areas.',
            address: 'Jl. Pantai Sanur No. 12',
            country: 'Indonesia',
            latitude: -8.705234,
            longitude: 115.262876,
            bedrooms: 4,
            bathrooms: 3,
            maxGuests: 8,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Beach Access', 'Kitchen', 'Garden', 'Staff', 'TV', 'Kayak']),
            isPublished: true,
            hostId: 1,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Family Villa Sanur Beach',
            type: 'Villa',
            price: 1200000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: false,
            description: 'Spacious family villa in Sanur residential area. Three bedrooms, private pool, and tropical garden create comfortable retreat. Features open living area, fully equipped kitchen, and covered terrace. Located minutes walk to beach, restaurants, and beachfront walking path. The villa includes daily housekeeping and optional nanny service. Perfect for families with children seeking safe, peaceful Bali experience with easy beach access, calm waters for swimming, and family-friendly atmosphere.',
            address: 'Jl. Danau Tamblingan, Sanur',
            country: 'Indonesia',
            latitude: -8.706123,
            longitude: 115.261765,
            bedrooms: 3,
            bathrooms: 3,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Housekeeping', 'TV', 'BBQ']),
            isPublished: true,
            hostId: 2,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Comfortable Apartment Sanur',
            type: 'Apartment',
            price: 650000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Modern 1-bedroom apartment in Sanur complex with shared pool. Features contemporary design, kitchenette, and balcony with garden view. Located in quiet compound near beach, restaurants, and supermarkets. The apartment includes WiFi, air conditioning, and weekly housekeeping. Building offers secure parking and 24-hour security. Ideal for couples or solo travelers wanting affordable Sanur base with pool facilities, peaceful neighborhood, and proximity to beach and dining options.',
            address: 'Jl. Bypass Ngurah Rai, Sanur',
            country: 'Indonesia',
            latitude: -8.707012,
            longitude: 115.260654,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchenette', 'TV', 'Parking', 'Balcony']),
            isPublished: true,
            hostId: 3,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },

        // Bali - Kuta (3 properties)
        {
            name: 'Surf Guesthouse Kuta Beach',
            type: 'Guesthouse',
            price: 500000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
            isGuestFavorite: false,
            description: 'Budget-friendly guesthouse steps from famous Kuta Beach. Features clean, comfortable rooms with air conditioning and en-suite bathrooms. Shared rooftop terrace offers sunset views and social atmosphere. Located in vibrant area near surf breaks, beach clubs, restaurants, and nightlife. Includes breakfast, WiFi, and surf board rental. Perfect for backpackers, surf enthusiasts, or budget travelers wanting affordable Kuta beach access with social vibe and essential amenities.',
            address: 'Jl. Pantai Kuta No. 88',
            country: 'Indonesia',
            latitude: -8.719876,
            longitude: 115.169234,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Breakfast', 'Rooftop', 'Surf Storage', 'TV']),
            isPublished: true,
            hostId: 4,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Modern Hotel Room Kuta',
            type: 'Hotel',
            price: 750000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
            isGuestFavorite: false,
            description: 'Contemporary hotel room in Kuta center. Features modern design, comfortable bed, and private bathroom with rain shower. Hotel offers rooftop pool, restaurant, and bar with ocean views. Located minutes from Kuta Beach, shopping malls, and Ngurah Rai Airport. Daily breakfast and room service included. Perfect for travelers wanting hotel comfort and services with beach proximity, easy airport access, and vibrant nightlife within walking distance.',
            address: 'Jl. Legian No. 45',
            country: 'Indonesia',
            latitude: -8.720765,
            longitude: 115.168123,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
                'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Breakfast', 'Restaurant', 'Bar', 'TV', 'Airport Transfer']),
            isPublished: true,
            hostId: 5,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Beachfront Apartment Kuta',
            type: 'Apartment',
            price: 850000,
            nights: 2,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: true,
            description: 'Spacious 2-bedroom apartment with direct beach access in Kuta. Features modern furnishings, fully equipped kitchen, and large balcony with ocean views. Located in beachfront complex with swimming pool and restaurant. Walking distance to beach clubs, shopping, and dining. The apartment includes WiFi, air conditioning, and parking. Ideal for families or groups wanting self-catering beachfront accommodation with hotel-like amenities in prime Kuta location.',
            address: 'Jl. Pantai Kuta Selatan',
            country: 'Indonesia',
            latitude: -8.721654,
            longitude: 115.167012,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Beach Access', 'Kitchen', 'Parking', 'TV', 'Ocean View']),
            isPublished: true,
            hostId: 6,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // Surabaya - Pakuwon City (1 property)
        {
            name: 'Modern Apartment Pakuwon City',
            type: 'Apartment',
            price: 650000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            description: 'Contemporary apartment in prestigious Pakuwon City integrated complex. Features 2 bedrooms, modern furnishings, and city view. Located in building with direct access to shopping mall, restaurants, and entertainment. The apartment includes full kitchen, WiFi, and parking. Building offers swimming pool and fitness center. Perfect for business travelers or families visiting Surabaya wanting convenient lifestyle with shopping, dining, and business facilities within integrated development.',
            address: 'Pakuwon City, Jl. Lontar',
            country: 'Indonesia',
            latitude: -7.299234,
            longitude: 112.665876,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Mall Access']),
            isPublished: true,
            hostId: 7,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },

        // Surabaya - Citraland (1 property)
        {
            name: 'Family House Citraland',
            type: 'House',
            price: 800000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: false,
            description: 'Comfortable 3-bedroom house in Citraland residential area. Features spacious living areas, full kitchen, and small garden. Located in secure gated community near Citraland shopping center and waterpark. The house includes air conditioning, WiFi, and parking for two cars. Close to international schools and business districts. Ideal for families relocating to Surabaya or groups needing suburban accommodation with access to entertainment, shopping, and family facilities.',
            address: 'Citraland, Jl. Waterpark Boulevard',
            country: 'Indonesia',
            latitude: -7.296543,
            longitude: 112.667234,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Garden', 'Parking', 'TV', 'Security']),
            isPublished: true,
            hostId: 8,
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Surabaya - Galaxy Mall (1 property)
        {
            name: 'Studio Apartment Galaxy Mall',
            type: 'Apartment',
            price: 450000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Compact studio apartment near Galaxy Mall shopping center. Features efficient layout with kitchenette, comfortable bed, and modern bathroom. Located in building with swimming pool near shopping, restaurants, and entertainment. The apartment includes WiFi, air conditioning, and parking access. Close to business districts and public transportation. Perfect for solo travelers or business visitors seeking affordable, functional accommodation in central Surabaya with mall proximity.',
            address: 'Jl. Dharmahusada Indah',
            country: 'Indonesia',
            latitude: -7.297876,
            longitude: 112.668345,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchenette', 'Parking', 'TV']),
            isPublished: true,
            hostId: 9,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },

        // Surabaya - Darmo (1 property)
        {
            name: 'Executive Apartment Darmo',
            type: 'Apartment',
            price: 700000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            isGuestFavorite: false,
            description: 'Executive 2-bedroom apartment in Darmo business area. Features modern design, fully equipped kitchen, and comfortable living space. Located in premium building near offices, embassies, and upscale shopping. Building offers swimming pool, gym, and 24-hour security. The apartment includes high-speed WiFi and parking. Close to hospitals and international restaurants. Perfect for business executives or families seeking quality accommodation in Surabaya\'s established residential and business district.',
            address: 'Jl. Raya Darmo No. 88',
            country: 'Indonesia',
            latitude: -7.295432,
            longitude: 112.669456,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Gym', 'Parking', 'TV', 'Security']),
            isPublished: true,
            hostId: 10,
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },

        // Surabaya - Rungkut (1 property)
        {
            name: 'Budget Apartment Rungkut',
            type: 'Apartment',
            price: 400000,
            nights: 2,
            rating: 4.3,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Affordable studio apartment in Rungkut residential area. Features basic amenities including bed, kitchenette, and bathroom. Located in quiet neighborhood near industrial estates and universities. The apartment includes WiFi and air conditioning. Close to public transportation and local markets. Suitable for budget travelers, students, or workers needing simple, clean accommodation in eastern Surabaya with easy access to industrial areas and educational institutions.',
            address: 'Jl. Rungkut Industri Raya',
            country: 'Indonesia',
            latitude: -7.298765,
            longitude: 112.670567,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV']),
            isPublished: true,
            hostId: 11,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },

        // Bandung - Dago (1 property)
        {
            name: 'Villa Resort Dago Pakar',
            type: 'Villa',
            price: 1100000,
            nights: 2,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            isGuestFavorite: true,
            description: 'Mountain villa in cool Dago Pakar area with stunning views. Features 3 bedrooms, private pool, and spacious garden. Property includes modern kitchen, cozy living areas, and outdoor terrace. Located in exclusive hillside location near tea plantations and natural attractions. Perfect for families or groups seeking weekend escape from Jakarta with fresh mountain air, nature activities, and proximity to Bandung\'s shopping and culinary scene.',
            address: 'Jl. Dago Pakar Raya No. 12',
            country: 'Indonesia',
            latitude: -6.843567,
            longitude: 107.613234,
            bedrooms: 3,
            bathrooms: 2,
            maxGuests: 6,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Private Pool', 'Kitchen', 'Garden', 'Mountain View', 'Parking', 'TV', 'BBQ']),
            isPublished: true,
            hostId: 12,
            createdAt: new Date('2024-03-28').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },

        // Bandung - Setiabudhi (1 property)
        {
            name: 'Modern Apartment Setiabudhi',
            type: 'Apartment',
            price: 650000,
            nights: 2,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            isGuestFavorite: false,
            description: 'Contemporary 2-bedroom apartment in upscale Setiabudhi area. Features modern furnishings, full kitchen, and city view. Located in building with swimming pool near shopping outlets and restaurants. The apartment includes WiFi, air conditioning, and parking. Close to Bandung Institute of Technology and factory outlets. Ideal for families or groups visiting Bandung for shopping, business, or leisure with comfortable accommodation in premium residential area.',
            address: 'Jl. Setiabudhi No. 228',
            country: 'Indonesia',
            latitude: -6.867890,
            longitude: 107.598765,
            bedrooms: 2,
            bathrooms: 2,
            maxGuests: 4,
            petsAllowed: false,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Pool', 'Kitchen', 'Parking', 'TV', 'City View']),
            isPublished: true,
            hostId: 13,
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },

        // Bandung - Pasteur (1 property)
        {
            name: 'Cozy Guesthouse Pasteur',
            type: 'Guesthouse',
            price: 450000,
            nights: 2,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
            isGuestFavorite: false,
            description: 'Comfortable guesthouse in Pasteur area near hospitals and universities. Features clean rooms with en-suite bathrooms and shared common areas. Located in residential neighborhood with easy access to shopping centers and public transportation. Daily breakfast included. The guesthouse offers WiFi and parking. Perfect for medical tourists visiting nearby hospitals, families visiting students, or budget travelers wanting affordable Bandung accommodation with local hospitality.',
            address: 'Jl. Dr. Djunjunan No. 45',
            country: 'Indonesia',
            latitude: -6.897654,
            longitude: 107.589012,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Breakfast', 'Parking', 'TV']),
            isPublished: true,
            hostId: 14,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },

        // Bandung - Buah Batur (1 property)
        {
            name: 'Mountain House Buah Batur',
            type: 'House',
            price: 750000,
            nights: 2,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            isGuestFavorite: false,
            description: 'Charming house in elevated Buah Batur area with panoramic city views. Features 2 bedrooms, spacious living room, and outdoor seating area. Located in quiet hillside neighborhood with cool mountain climate. The house includes full kitchen, WiFi, and parking. Close to Bandung city center yet away from crowds. Ideal for couples or small families seeking peaceful retreat with spectacular views, fresh air, and easy access to Bandung attractions.',
            address: 'Jl. Buah Batu No. 157',
            country: 'Indonesia',
            latitude: -6.943210,
            longitude: 107.634567,
            bedrooms: 2,
            bathrooms: 1,
            maxGuests: 4,
            petsAllowed: true,
            checkInTime: '14:00',
            checkOutTime: '12:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchen', 'Parking', 'TV', 'City View', 'Outdoor Seating']),
            isPublished: true,
            hostId: 15,
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-04-08').toISOString(),
        },

        // Bandung - Cihampelas (1 property)
        {
            name: 'Studio Apartment Cihampelas',
            type: 'Apartment',
            price: 500000,
            nights: 2,
            rating: 4.3,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            isGuestFavorite: false,
            description: 'Practical studio apartment on famous Cihampelas shopping street. Features efficient layout with kitchenette, comfortable bed, and modern bathroom. Located above shops and restaurants in busy commercial area. The apartment includes WiFi and air conditioning. Walking distance to Cihampelas Walk mall and numerous factory outlets. Perfect for shopping enthusiasts, solo travelers, or budget-conscious visitors wanting central Bandung location with immediate access to shopping and dining.',
            address: 'Jl. Cihampelas No. 160',
            country: 'Indonesia',
            latitude: -6.895432,
            longitude: 107.603456,
            bedrooms: 1,
            bathrooms: 1,
            maxGuests: 2,
            petsAllowed: false,
            checkInTime: '15:00',
            checkOutTime: '11:00',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
                'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800'
            ]),
            amenities: JSON.stringify(['WiFi', 'AC', 'Kitchenette', 'TV']),
            isPublished: true,
            hostId: 16,
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
    ];

    await db.insert(properties).values(sampleProperties);
    
    console.log('✅ Properties seeder completed successfully - 50 Indonesian listings created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});