import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const sampleReviews = [
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'James Anderson',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 5.0,
            cleanliness: 5.0,
            accuracy: 4.8,
            communication: 5.0,
            location: 4.9,
            value: 4.7,
            comment: 'The place is very beautiful with stunning ocean views from every corner. The infinity pool is absolutely breathtaking, especially during sunset. We spent hours just relaxing by the pool. The villa is well-maintained and the staff was incredibly helpful with our requests. Highly recommend for a romantic getaway!',
            createdAt: new Date(now.getTime() - (150 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (150 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Dewi Lestari',
            userAvatar: null,
            rating: 4.9,
            cleanliness: 5.0,
            accuracy: 4.8,
            communication: 4.9,
            location: 5.0,
            value: 4.8,
            comment: 'I love the view from the infinity pool! You can see the entire coastline and watch surfers at Uluwatu beach. The villa\'s modern design blends perfectly with the natural surroundings. Our host was very responsive and provided excellent restaurant recommendations. Only small note - the road to get here is quite steep but worth it!',
            createdAt: new Date(now.getTime() - (120 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (120 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Sophie Chen',
            userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
            rating: 5.0,
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.8,
            value: 4.9,
            comment: 'Amazing villa, perfect for a romantic getaway. The master bedroom has direct views of the ocean and waking up to that view was magical. The outdoor shower is a unique experience. The villa is private and peaceful, yet close enough to Seminyak and Uluwatu attractions. We celebrated our anniversary here and it was unforgettable.',
            createdAt: new Date(now.getTime() - (105 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (105 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Budi Santoso',
            userAvatar: null,
            rating: 4.8,
            cleanliness: 4.9,
            accuracy: 4.7,
            communication: 5.0,
            location: 4.6,
            value: 4.8,
            comment: 'The staff was incredibly helpful and friendly throughout our stay. They arranged airport transfers, daily housekeeping, and even helped us book a private dinner on the cliff. The villa itself is stunning with high-end finishes and comfortable furnishings. The kitchen is fully equipped. This is luxury living at its finest!',
            createdAt: new Date(now.getTime() - (75 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (75 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Marco Rossi',
            userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            rating: 4.9,
            cleanliness: 4.8,
            accuracy: 4.9,
            communication: 4.7,
            location: 5.0,
            value: 4.9,
            comment: 'Great location near Uluwatu temple and the famous beach clubs. We could easily visit Sundays Beach Club, Single Fin, and the Uluwatu Temple within 15 minutes. The villa provides the perfect base for exploring while offering complete privacy. The sunset views are unbeatable. Will definitely return!',
            createdAt: new Date(now.getTime() - (60 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (60 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Emma Thompson',
            userAvatar: null,
            rating: 5.0,
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 4.9,
            location: 4.8,
            value: 5.0,
            comment: 'Spectacular villa with incredible architecture! The open-plan design and floor-to-ceiling windows create an amazing sense of space. The infinity pool seems to merge with the ocean horizon. We had a group of 6 and everyone had their own comfortable room. The outdoor areas are perfect for entertaining. Worth every penny!',
            createdAt: new Date(now.getTime() - (30 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (30 * 24 * 60 * 60 * 1000)).toISOString(),
        },
        {
            propertyId: 98,
            carId: null,
            userId: null,
            userName: 'Andi Wijaya',
            userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            rating: 5.0,
            cleanliness: 5.0,
            accuracy: 5.0,
            communication: 5.0,
            location: 4.9,
            value: 4.8,
            comment: 'Outstanding experience from start to finish. The villa exceeded our expectations in every way. The attention to detail, the quality of amenities, and the service level are all 5-star. The location on the cliff is dramatic and beautiful. We used the villa\'s chef service and the meals were restaurant-quality. This is a must-stay in Bali!',
            createdAt: new Date(now.getTime() - (14 * 24 * 60 * 60 * 1000)).toISOString(),
            updatedAt: new Date(now.getTime() - (14 * 24 * 60 * 60 * 1000)).toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder for property 98 completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});