import { db } from '@/db';
import { rooms } from '@/db/schema';

async function main() {
    const sampleRooms = [
        {
            propertyId: 1,
            name: 'Deluxe Suite',
            type: 'Deluxe Suite',
            pricePerNight: 350000,
            maxGuests: 2,
            size: 45,
            beds: JSON.stringify({ king: 1, queen: 0, single: 0, double: 0 }),
            amenities: JSON.stringify(['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Safe', 'Work Desk']),
            available: true,
            roomNumber: 101,
            inRoomAmenities: JSON.stringify(['King Bed', 'Smart TV', 'Mini Fridge', 'Coffee Maker']),
            bathroomFacilities: JSON.stringify(['Rain Shower', 'Bathtub', 'Premium Toiletries', 'Hair Dryer']),
            additionalFeatures: JSON.stringify(['City View', 'Balcony', 'Blackout Curtains']),
            technologyComfort: JSON.stringify(['Smart TV', 'WiFi', 'USB Charging Ports', 'Safe']),
            extraServices: JSON.stringify(['Daily Housekeeping', 'Room Service', 'Laundry Service']),
            hasLock: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            name: 'Standard Room',
            type: 'Standard Room',
            pricePerNight: 250000,
            maxGuests: 2,
            size: 30,
            beds: JSON.stringify({ king: 0, queen: 1, single: 0, double: 0 }),
            amenities: JSON.stringify(['WiFi', 'TV', 'Air Conditioning']),
            available: true,
            roomNumber: 102,
            inRoomAmenities: JSON.stringify(['Queen Bed', 'TV', 'Mini Fridge']),
            bathroomFacilities: JSON.stringify(['Shower', 'Toiletries', 'Hair Dryer']),
            additionalFeatures: JSON.stringify(['Window View', 'Desk']),
            technologyComfort: JSON.stringify(['TV', 'WiFi']),
            extraServices: JSON.stringify(['Daily Housekeeping']),
            hasLock: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            name: 'Family Room',
            type: 'Family Room',
            pricePerNight: 450000,
            maxGuests: 4,
            size: 55,
            beds: JSON.stringify({ king: 1, queen: 0, single: 2, double: 0 }),
            amenities: JSON.stringify(['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Coffee Maker']),
            available: true,
            roomNumber: 201,
            inRoomAmenities: JSON.stringify(['King Bed', 'Twin Beds', 'Smart TV', 'Mini Fridge', 'Coffee Maker', 'Sofa']),
            bathroomFacilities: JSON.stringify(['Rain Shower', 'Bathtub', 'Toiletries', 'Hair Dryer']),
            additionalFeatures: JSON.stringify(['City View', 'Balcony', 'Extra Space']),
            technologyComfort: JSON.stringify(['Smart TV', 'WiFi', 'USB Charging Ports']),
            extraServices: JSON.stringify(['Daily Housekeeping', 'Room Service']),
            hasLock: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            name: 'Premium Studio',
            type: 'Premium Studio',
            pricePerNight: 300000,
            maxGuests: 2,
            size: 35,
            beds: JSON.stringify({ king: 1, queen: 0, single: 0, double: 0 }),
            amenities: JSON.stringify(['WiFi', 'TV', 'Air Conditioning', 'Work Desk', 'Safe']),
            available: true,
            roomNumber: 202,
            inRoomAmenities: JSON.stringify(['King Bed', 'Smart TV', 'Mini Fridge', 'Coffee Maker', 'Microwave']),
            bathroomFacilities: JSON.stringify(['Rain Shower', 'Premium Toiletries', 'Hair Dryer']),
            additionalFeatures: JSON.stringify(['City View', 'Work Desk', 'Kitchenette']),
            technologyComfort: JSON.stringify(['Smart TV', 'WiFi', 'Work Desk', 'Safe', 'USB Charging Ports']),
            extraServices: JSON.stringify(['Daily Housekeeping', 'Room Service']),
            hasLock: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            propertyId: 1,
            name: 'Budget Room',
            type: 'Budget Room',
            pricePerNight: 180000,
            maxGuests: 2,
            size: 25,
            beds: JSON.stringify({ king: 0, queen: 0, single: 0, double: 1 }),
            amenities: JSON.stringify(['WiFi', 'TV', 'Air Conditioning']),
            available: true,
            roomNumber: 103,
            inRoomAmenities: JSON.stringify(['Double Bed', 'TV']),
            bathroomFacilities: JSON.stringify(['Shower', 'Basic Toiletries']),
            additionalFeatures: JSON.stringify(['Window View']),
            technologyComfort: JSON.stringify(['TV', 'WiFi']),
            extraServices: JSON.stringify(['Daily Housekeeping']),
            hasLock: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(rooms).values(sampleRooms);
    
    console.log('✅ Rooms seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});